config/routes.rb
Octo::Application.routes.draw do
  resources :cephalopods

  

end

app/models/cephalopod.rb
class Cephalopod < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def shard_file
    'config/shards.yml'
  end

  def shard_chache_time
    50.seconds
  end

  def load_shard_value
    File.read(File.expand_path(shard_file, Rails.root))
  end

  def get_shard_value
    return @shard if @shard
    unless cached
      update_last_sync
      ENV['shard'] = "#{load_shard_value}"
    end
    @shard = HashWithIndifferentAccess.new(YAML.load(ENV['shard']))[:octopus][:development]
  end

  before_action :reconfigure_shards

  def reconfigure_shards
    sh = get_shard_value
    Octopus.shards = sh
    ActiveRecord::Base.connection.initialize_replication(sh)
    ActiveRecord::Base.connection.instance_eval{@slave_index = Random.rand(0...sh.count)}

    Cephalopod.first
    conn = Thread.current[:'octopus.current_model'].connection
    @lcs = conn.instance_variables.inject({})do |memo, var|
      memo[var] = conn.instance_variable_get(var)
      memo
    end
  end

  def cached
    last_sync && last_sync > shard_chache_time.ago
  end

  def last_sync
    @last_sync ||= ENV['last_sync'].blank? ? nil : Time.at(ENV['last_sync'].to_i)
  end

  def update_last_sync
    ENV['last_sync'] = "#{Time.now.to_i}"
  end

end

app/controllers/cephalopods_controller.rb
class CephalopodsController < ApplicationController
  before_action :set_cephalopod, only: [:show, :edit, :update, :destroy]

  # GET /cephalopods
  # GET /cephalopods.json
  def index
    @cephalopods = Cephalopod.all
  end

  # GET /cephalopods/1
  # GET /cephalopods/1.json
  def show
  end

  # GET /cephalopods/new
  def new
    @cephalopod = Cephalopod.new
  end

  # GET /cephalopods/1/edit
  def edit
  end

  # POST /cephalopods
  # POST /cephalopods.json
  def create
    @cephalopod = Cephalopod.new(cephalopod_params)

    respond_to do |format|
      if @cephalopod.save
        format.html { redirect_to @cephalopod, notice: 'Cephalopod was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cephalopod }
      else
        format.html { render action: 'new' }
        format.json { render json: @cephalopod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cephalopods/1
  # PATCH/PUT /cephalopods/1.json
  def update
    respond_to do |format|
      if @cephalopod.update(cephalopod_params)
        format.html { redirect_to @cephalopod, notice: 'Cephalopod was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cephalopod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cephalopods/1
  # DELETE /cephalopods/1.json
  def destroy
    @cephalopod.destroy
    respond_to do |format|
      format.html { redirect_to cephalopods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cephalopod
      @cephalopod = Cephalopod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cephalopod_params
      params.require(:cephalopod).permit(:name, :tentacles)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cephalopods_helper.rb
module CephalopodsHelper
end

app/views/cephalopods/_form.html.erb
<%= form_for(@cephalopod) do |f| %>
  <% if @cephalopod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cephalopod.errors.count, "error") %> prohibited this cephalopod from being saved:</h2>

      <ul>
      <% @cephalopod.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tentacles %><br>
    <%= f.number_field :tentacles %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cephalopods/edit.html.erb
<h1>Editing cephalopod</h1>

<%= render 'form' %>

<%= link_to 'Show', @cephalopod %> |
<%= link_to 'Back', cephalopods_path %>

app/views/cephalopods/index.html.erb
<h1>Listing cephalopods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tentacles</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cephalopods.each do |cephalopod| %>
      <tr>
        <td><%= cephalopod.name %></td>
        <td><%= cephalopod.tentacles %></td>
        <td><%= link_to 'Show', cephalopod %></td>
        <td><%= link_to 'Edit', edit_cephalopod_path(cephalopod) %></td>
        <td><%= link_to 'Destroy', cephalopod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cephalopod', new_cephalopod_path %>

app/views/cephalopods/new.html.erb
<h1>New cephalopod</h1>

<%= render 'form' %>

<%= link_to 'Back', cephalopods_path %>

app/views/cephalopods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cephalopod.name %>
</p>

<p>
  <strong>Tentacles:</strong>
  <%= @cephalopod.tentacles %>
</p>

<%= link_to 'Edit', edit_cephalopod_path(@cephalopod) %> |
<%= link_to 'Back', cephalopods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Octo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

[[<%= debug @shard %>]]

<%= yield %>

</body>
</html>